// eslint-disable-next-line no-undef
System.config({
    'paths': {
        'assets/*': './src/assets/*',
        'images': './src/assets/images',
        'navigation': './src/navigation',
        'navigation/*': './src/navigation/*',
        'screens': './src/screens',
        'screens/*': './src/screens/*',
        'splash': './src/modules/splash',
        'utils': './src/utils',
        'utils/*': './src/utils/*',
        'translations': './src/utils/translations',
        'translations/*': './src/utils/translations/*',
        'languages': './languages',
        'styles': './src/styles',
        'styles/*': './src/styles/*',
        'components': './src/components',
        'constant': './src/constant',
        'context': './src/context',
        'api': './src/API',
        'store': './src/store',
        'store/*': './src/store/*',
    },
});
