export const API_CALL = {
    BEGIN_API_CALL: 'BEGIN_API_CALL',
    API_CALL_SUCCESS: 'API_CALL_SUCCESS',
    CLEAR_API_CALL_ERROR: 'CLEAR_API_CALL_ERROR',
    API_CALL_ERROR: 'API_CALL_ERROR',
};



