export default {
    ERROR: 'ERROR',
    LOADING: 'LOADING',
    NOT_STARTED: 'NOT_STARTED',
    SUCCESS: 'SUCCESS',
    NETWORK_ERROR: 'NETWORK_ERROR',
    UNKNOWN: 'UNKNOWN',
    REQUEST_TIME_OUT: 'REQUEST_TIME_OUT',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVER_UNAVAILABLE: 'SERVER_UNAVAILABLE',
};
